In [ ]:
import numpy as np

# generated by ChatGPT 5.2
def multivariate_normal_density(x, mu, Sigma):
  """
  Returns the multivariate normal density:
  N(x | mu, Sigma)

  Parameters
  ----------
  x : (D,) array
  mu : (D,) array
  Sigma : (D,D) covariance matrix

  Returns
  -------
  float
      Density evaluated at x
  """

  x = np.asarray(x)
  mu = np.asarray(mu)
  Sigma = np.asarray(Sigma)

  D = mu.shape[0]

  Sigma_inv = np.linalg.inv(Sigma)
  det_Sigma = np.linalg.det(Sigma)

  diff = x - mu

  exponent = -0.5 * diff.T @ Sigma_inv @ diff
  normalization = 1 / np.sqrt((2*np.pi)**D * det_Sigma)

  return normalization * np.exp(exponent)


In [ ]:
from scipy.stats import multivariate_normal
import numpy as np

def compare_scipy():
  x = np.array([1.0, 2.0])
  mu = np.array([0.0, 0.0])

  print("Spherical Gaussian:")
  Sigma1 = 2 * np.eye(2)

  print("LLM  :", multivariate_normal_density(x, mu, Sigma1))
  print("SciPy :", multivariate_normal(mean=mu, cov=Sigma1).pdf(x))
  print()

  print("Diagonal Gaussian:")
  Sigma2 = np.diag([1.0, 3.0])

  print("LLM  :", multivariate_normal_density(x, mu, Sigma2))
  print("SciPy :", multivariate_normal(mean=mu, cov=Sigma2).pdf(x))
  print()

  print("Full-Covariance Gaussian:")
  Sigma3 = np.array([
    [2.0, 0.5],
    [0.5, 1.5]
  ])

  print("LLM  :", multivariate_normal_density(x, mu, Sigma3))
  print("SciPy :", multivariate_normal(mean=mu, cov=Sigma3).pdf(x))
  print()

compare_scipy()



Spherical Gaussian:
LLM  : 0.022799327319919294
SciPy : 0.022799327319919297

Diagonal Gaussian:
LLM  : 0.02861426591193669
SciPy : 0.02861426591193669

Full-Covariance Gaussian:
LLM  : 0.02454336107675682
SciPy : 0.02454336107675683



In [ ]:
class MultivariateNormal:

  def __init__(self, mean, cov):
    self.mean = np.asarray(mean)
    self.cov = np.asarray(cov)
    self.D = self.mean.shape[0]

  def log_pdf(self, x):
    x = np.asarray(x)

    Sigma_inv = np.linalg.inv(self.cov)
    det_Sigma = np.linalg.det(self.cov)

    diff = x - self.mean

    exponent = -0.5 * diff.T @ Sigma_inv @ diff
    log_norm = -0.5 * (self.D*np.log(2*np.pi) + np.log(det_Sigma))

    return log_norm + exponent

  def rvs(self, shape=()):

    if isinstance(shape, int):
      shape = (shape,)

    return np.random.multivariate_normal(
      self.mean,
      self.cov,
      size=shape
    )


In [ ]:
mu = np.array([0.0, 0.0])
Sigma = np.array([
    [2.0, 0.5],
    [0.5, 1.5]
])

my_dist = MultivariateNormal(mu, Sigma)

print("log_pdf at x:")

x = np.array([1.0, 2.0])

print(my_dist.log_pdf(x))

print()
print("Samples:")
print(my_dist.rvs(5))
print(my_dist.rvs((2,3)))


log_pdf at x:
-3.7073138858849486

Samples:
[[-1.51212774 -1.38663451]
 [-2.55078529 -2.21155167]
 [ 0.04432547  3.11908325]
 [ 0.19068713 -0.59427348]
 [ 0.13995329  0.84565433]]
[[[-0.30759354 -0.52180329]
  [-1.24391233 -1.56233081]
  [-1.20979221 -0.43598774]]

 [[-1.44639766 -0.48942049]
  [-1.43910708  1.18603463]
  [ 0.66025773 -0.44525725]]]
